---
abstract: 'Quotes strings suitably for rfc2822 local part'
author:
  - 'David Bremner <ddb@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Convert-YText
provides:
  Convert::YText:
    file: lib/Convert/YText.pm
    version: v0.1.2
requires:
  Test::More: 0
resources:
  homepage: http://pivot.cs.unb.ca/git/?p=convert-ytext.git;a=summary
version: v0.1.2
